//
//  CheckoutPresenter.swift
//  smartPOS
//
//  Created by I Am Focused on 18/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CheckoutPresentationLogic
{
    func presentFetchedOrder(response: ListMenuItems.FetchMenuItems.Response)
}

class CheckoutPresenter: CheckoutPresentationLogic
{
  weak var viewController: CheckoutDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchedOrder(response: ListMenuItems.FetchMenuItems.Response) {
    var displayedMenuItems: [ListMenuItems.FetchMenuItems.ViewModel.DisplayedMenuItem] = []
    for menuItem in response.menuItems {
        let displayedMenuItem = ListMenuItems.FetchMenuItems.ViewModel.DisplayedMenuItem(id: menuItem.id, name: menuItem.name, price: menuItem.price)
        displayedMenuItems.append(displayedMenuItem)
    }
    let viewModel = ListMenuItems.FetchMenuItems.ViewModel(displayedMenuItems: displayedMenuItems)
    viewController?.displayFetchedMenuItems(viewModel: viewModel)
  }
}
