//
//  CheckoutRouter.swift
//  smartPOS
//
//  Created by I Am Focused on 18/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CheckoutRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
    func routeToCreateOrder(segue: UIStoryboardSegue?)
    func routeToShowOrder(segue: UIStoryboardSegue?)
}

protocol CheckoutDataPassing {
  var dataStore: CheckoutDataStore? { get }
}

class CheckoutRouter: NSObject, CheckoutRoutingLogic, CheckoutDataPassing {
    func routeToCreateOrder(segue: UIStoryboardSegue?) {
        print("routeToCreateOrder")
    }
    
    func routeToShowOrder(segue: UIStoryboardSegue?) {
        print("routeToShowOrder")
    }
    
  weak var viewController: CheckoutViewController?
  var dataStore: CheckoutDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CheckoutViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CheckoutDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
