//
//  CheckoutModels.swift
//  smartPOS
//
//  Created by I Am Focused on 18/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Checkout {
  // MARK: Use cases
  
  enum Something {
    struct Request {
    }
    struct Response {
    }
    struct ViewModel {
    }
  }
}


enum ListMenuItems {
    struct DisplayedMenuItem {
        var id: String
        var name: String
        var price: Double
    }
    enum FetchMenuItems{
        struct Request {
                
        }
        struct Response {
            var menuItems: [MenuItem]
            var error: MenuItemErrors?
        }
        struct ViewModel {
            var displayedMenuItems: [DisplayedMenuItem]
            var error: MenuItemErrors?
        }
    }
}
