//
//  CheckoutPresenter.swift
//  smartPOS
//
//  Created by I Am Focused on 18/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CheckoutPresentationLogic {
    func presentFetchedOrder(response: Checkout.FetchMenuItems.Response)
    func presentCreatedOrderItem(response: Checkout.CreateOrderItem.Response)
    func presentCreateOrderAndOrderItem(response: Checkout.CreateOrderAndOrderItems.Response)
}

class CheckoutPresenter: CheckoutPresentationLogic {
    
    
    weak var viewController: CheckoutDisplayLogic?
  
    // MARK: Do something
  
    func presentFetchedOrder(response: Checkout.FetchMenuItems.Response) {
        var displayedMenuItems: [Checkout.DisplayedMenuItem] = []
        for menuItem in response.menuItems {
            let displayedMenuItem = Checkout.DisplayedMenuItem(id: menuItem.id, name: menuItem.name, price: menuItem.price)
            displayedMenuItems.append(displayedMenuItem)
        }
        let viewModel = Checkout.FetchMenuItems.ViewModel(displayedMenuItems: displayedMenuItems)
        viewController?.displayFetchedMenuItems(viewModel: viewModel)
    }
    
    func presentCreatedOrderItem(response: Checkout.CreateOrderItem.Response) {
//        var displayedOrderItems: [Checkout.DisplayedOrderItem] = []
        let orderItem = response.orderItem
        let viewModel = Checkout.CreateOrderItem.ViewModel(orderItem: orderItem)
        viewController?.displayCreatedOrderItem(viewModel: viewModel)
    }
    func presentCreateOrderAndOrderItem(response: Checkout.CreateOrderAndOrderItems.Response) {
        let orderItems = response.orderItems
        let order = response.order
        let viewModel = Checkout.CreateOrderAndOrderItems.ViewModel(order: order, orderItems: orderItems, error: response.error)
        viewController?.displayCreatedOrderAndOrderItems(viewModel: viewModel)
    }
}
