//
//  CheckoutInteractor.swift
//  smartPOS
//
//  Created by I Am Focused on 18/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CheckoutBusinessLogic {
    func fetchMenuItems(request: ListMenuItems.FetchMenuItems.Request)
}

protocol CheckoutDataStore {
    var menuItems: [MenuItem]? { get }
}

class CheckoutInteractor: CheckoutBusinessLogic, CheckoutDataStore {
    var menuItems: [MenuItem]?
    var presenter: CheckoutPresentationLogic?
    //  var worker: CheckoutWorker? = CheckoutWorker()
    var menuItemsWorker: MenuItemsWorker? = MenuItemsWorker(menuItemsStore: MenuItemsMemStore())
    // var name: String = ""
  
    // MARK: Fetch MenuItems
  
    func fetchMenuItems(request: ListMenuItems.FetchMenuItems.Request) {
        menuItemsWorker?.fetchMenuItems { (menuItems) -> Void in
            self.menuItems = menuItems
            let response = ListMenuItems.FetchMenuItems.Response(menuItems: menuItems)
            self.presenter?.presentFetchedOrder(response: response)
        }
    }
}
