//
//  OrdersPageViewController.swift
//  smartPOS
//
//  Created by I Am Focused on 17/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SkeletonView
protocol OrdersPageDisplayLogic: class {
    func displayOrders(viewModel: OrdersPage.FetchOrders.ViewModel)
    func displaySearchOrders(viewModel: OrdersPage.SearchOrders.ViewModel)
    func displayOrdersByStatus(viewModel: OrdersPage.FetchOrdersByStatus.ViewModel)
    func displayRefreshedOrders(viewModel: OrdersPage.RefreshOrders.ViewModel)
}

class OrdersPageViewController: UIViewController, OrdersPageDisplayLogic {
    var interactor: OrdersPageBusinessLogic?
    var router: (NSObjectProtocol & OrdersPageRoutingLogic & OrdersPageDataPassing)?
    
    @IBOutlet var segmentedControlStatus: UISegmentedControl!
    
    @IBOutlet weak var ordersConllectionView: UIView!
    @IBOutlet weak var orderDetailView: UIView!
    
    // MARK: - Variables
    var displayedOrders: [Order] = []
    
    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        view.showAnimatedGradientSkeleton()
        fetchOrders()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.setNavigationBarItem()
        
    }
  
    func displaySearchOrders(viewModel: OrdersPage.SearchOrders.ViewModel) {
        print("displaySearchOrders")
    }

    func displayOrdersByStatus(viewModel: OrdersPage.FetchOrdersByStatus.ViewModel) {
        print("displayOrdersByStatus")
    }
    
    func displayRefreshedOrders(viewModel: OrdersPage.RefreshOrders.ViewModel) {
        print("displayRefreshedOrders")
    }
}

// MARK: Fetch orders on screen load

extension OrdersPageViewController {
    // MARK: Fetch Data to display in the orders collection view

    func fetchOrders() {
        let restaurantId = APIConfig.restaurantId
        let query = "SALE"
        let pageNumber = 1
        let request = OrdersPage.FetchOrders.Request(restaurantId: restaurantId, query: query, pageNumber: pageNumber)
        interactor?.fetchOrders(request: request)
    }
    
    func displayOrders(viewModel: OrdersPage.FetchOrders.ViewModel) {
        view.hideSkeleton()
        // MARK: Need to do this func after display orders on collection view
        setupOrdersDisplay(viewModel: viewModel)
        print("displayOrders")
    }
    
    private func setupOrdersDisplay(viewModel: OrdersPage.FetchOrders.ViewModel) {
        guard viewModel.error == nil else {
            Alert.showUnableToRetrieveDataAlert(on: self)
            return
        }
        NotificationCenter.default.post(name: Notification.Name("FetchOrders"), object: viewModel)
    }
}



// MARK: Setup

private extension OrdersPageViewController {
    private func setup() {
        let viewController = self
        let interactor = OrdersPageInteractor()
        let presenter = OrdersPagePresenter()
        let router = OrdersPageRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor

    }
    
}
