//
//  OrdersPageRouter.swift
//  smartPOS
//
//  Created by I Am Focused on 17/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OrdersPageRoutingLogic {
    func showLaunchPage(for id: String)
}

protocol OrdersPageDataPassing {
  var dataStore: OrdersPageDataStore? { get }
}

class OrdersPageRouter: NSObject, OrdersPageRoutingLogic, OrdersPageDataPassing, RouterProtocol {

  weak var viewController: OrdersPageViewController?
  var dataStore: OrdersPageDataStore?
  
  // MARK: Routing
  
    func showLaunchPage(for id: String) {
//        let selectedOrder = dataStore?.orders?.first { $0.id == id }
//        guard let launch = selectedOrder else { return }
//
//        show(nibIdentifier: "SingleLaunchPageViewController") { (destinationVC: SingleLaunchPageViewController) in
//            var destinationDS = destinationVC.router!.dataStore!
//            self.passDataToLaunchPage(source: launch, destination: &destinationDS)
//        }
    }
    
    // MARK: Passing data
    
//    func passDataToLaunchPage(source: Order, destination: inout SingleLaunchPageDataStore) {
//        destination.launch = source
//    }
}
