//
//  OrdersLocalViewController.swift
//  smartPOS
//
//  Created by I Am Focused on 18/05/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OrdersLocalDisplayLogic: class {
    func displaySomething(viewModel: OrdersLocal.Something.ViewModel)
}

class OrdersLocalViewController: UIViewController, OrdersLocalDisplayLogic {
    var interactor: OrdersLocalBusinessLogic?
    var router: (NSObjectProtocol & OrdersLocalRoutingLogic & OrdersLocalDataPassing)?

    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = OrdersLocalInteractor()
        let presenter = OrdersLocalPresenter()
        let router = OrdersLocalRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
  
    // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
  
    // MARK: Do something
  
    // @IBOutlet weak var nameTextField: UITextField!
  
    func doSomething() {
        let request = OrdersLocal.Something.Request()
        interactor?.doSomething(request: request)
    }
  
    func displaySomething(viewModel: OrdersLocal.Something.ViewModel) {
        // nameTextField.text = viewModel.name
    }
}
