//
//  OrdersLocalRouter.swift
//  smartPOS
//
//  Created by I Am Focused on 18/05/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OrdersLocalRoutingLogic {
    // func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol OrdersLocalDataPassing {
    var dataStore: OrdersLocalDataStore? { get }
}

class OrdersLocalRouter: NSObject, OrdersLocalRoutingLogic, OrdersLocalDataPassing {
    weak var viewController: OrdersLocalViewController?
    var dataStore: OrdersLocalDataStore?

    // MARK: Routing

    // func routeToSomewhere(segue: UIStoryboardSegue?)
    // {
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    // }

    // MARK: Navigation

    // func navigateToSomewhere(source: OrdersLocalViewController, destination: SomewhereViewController)
    // {
    //  source.show(destination, sender: nil)
    // }

    // MARK: Passing data

    // func passDataToSomewhere(source: OrdersLocalDataStore, destination: inout SomewhereDataStore)
    // {
    //  destination.name = source.name
    // }
}
