//
//  OrdersLocalModels.swift
//  smartPOS
//
//  Created by I Am Focused on 18/05/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OrdersLocal {
    // MARK: Use cases

    enum Something {
        struct Request {}

        struct Response {}

        struct ViewModel {}
    }
}
