//
//  OrdersLocalPresenter.swift
//  smartPOS
//
//  Created by I Am Focused on 18/05/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OrdersLocalPresentationLogic {
    func presentSomething(response: OrdersLocal.Something.Response)
}

class OrdersLocalPresenter: OrdersLocalPresentationLogic {
    weak var viewController: OrdersLocalDisplayLogic?

    // MARK: Do something

    func presentSomething(response: OrdersLocal.Something.Response) {
        let viewModel = OrdersLocal.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
