//
//  OrdersLocalInteractor.swift
//  smartPOS
//
//  Created by I Am Focused on 18/05/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OrdersLocalBusinessLogic {
    func doSomething(request: OrdersLocal.Something.Request)
}

protocol OrdersLocalDataStore {
    // var name: String { get set }
}

class OrdersLocalInteractor: OrdersLocalBusinessLogic, OrdersLocalDataStore {
    var presenter: OrdersLocalPresentationLogic?
    var worker: OrdersLocalWorker?
    // var name: String = ""

    // MARK: Do something

    func doSomething(request: OrdersLocal.Something.Request) {
        worker = OrdersLocalWorker()
        worker?.doSomeWork()

        let response = OrdersLocal.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
