//
//  OrderDetailModels.swift
//  smartPOS
//
//  Created by I Am Focused on 18/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OrderDetail {
    // MARK: Use cases

    enum GetOrder {
        struct Request {
           var id: String?
        }

        struct Response {
            var order: Order?
            var error: OrderErrors?
        }

        struct ViewModel {
//            struct DisplayedOrder {
//
//            }
            
            var displayedOrder: Order
            var error: OrderErrors?
        }
    }
}
