//
//  OrderDetailPresenter.swift
//  smartPOS
//
//  Created by I Am Focused on 18/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OrderDetailPresentationLogic {
    func presentOrder(response: OrderDetail.GetOrder.Response)
}

class OrderDetailPresenter: OrderDetailPresentationLogic {
  weak var viewController: OrderDetailDisplayLogic?
  
  // MARK: Do present Order maybe some needed attr
  
  func presentOrder(response: OrderDetail.GetOrder.Response) {
    let order = response.order
    
//    let date = (launch.launchDateUTC).fromUTCToLocalDateTime()
//    let title = launch.missionName
//    var status = FlightStatus.upcoming
//    if let flightStatus = launch.launchSuccess {
//        status = flightStatus ? .success : .failure
//    }
//    let description = launch.details ?? ""
//    let flightNumber = "Flight Number #\(launch.flightNumber)"
//    let videoUrl = launch.links.youTubeVideoId
//    let imgUrl = launch.links.flickrImages
//    let displayedLaunch = SingleLaunchPage.GetLaunch.ViewModel.DisplayedLaunch(title: title, date: date, flightNumber: flightNumber, description: description, status: status, videoUrl: videoUrl, imgUrls: imgUrl)
//
//    let viewModel = SingleLaunchPage.GetLaunch.ViewModel(displayedLaunch: displayedLaunch)
//    viewController?.displayLaunch(viewModel: viewModel)
//
    
    
    
    let viewModel = OrderDetail.GetOrder.ViewModel(displayedOrder: order!)
    viewController?.displayOrder(viewModel: viewModel)
  }
}
