//
//  OrderDetailModels.swift
//  smartPOS
//
//  Created by I Am Focused on 18/04/2021.
//  Copyright (c) 2021 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OrderDetail {
    // MARK: Use cases

    enum GetOrder {
        struct Request {
            var id: String?
        }

        struct Response {
            var order: NestedOrder?
            var error: OrderErrors?
        }

        struct ViewModel {
            var order: Order?
            var orderItems: [OrderItem]?
            var error: OrderErrors?
        }
    }

    enum ConfirmOrder {
        struct Request {
            var id: String?
        }

        struct Response {
            var error: OrderErrors?
        }

        struct ViewModel {
            var error: OrderErrors?
        }
    }

    enum CompleteOrder {
        struct Request {
            var id: String?
        }

        struct Response {
            var error: OrderErrors?
        }

        struct ViewModel {
            var error: OrderErrors?
        }
    }

    enum RejectOrder {
        struct Request {
            var id: String?
            var orderItemIds: [String?]?
            var cashierNote: String?
        }

        struct Response {
            var error: OrderErrors?
        }

        struct ViewModel {
            var error: OrderErrors?
        }
    }
}
